ServerName localhost

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /websites/cheetah/frontend

    <Directory /websites/cheetah/frontend>
        Options FollowSymLinks MultiViews
        MultiviewsMatch Any
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/cheetah-error.log
    CustomLog ${APACHE_LOG_DIR}/cheetah-access.log combined
</VirtualHost>
